### ISSUE TITLE
Plug-in release?

### ISSUE THREAD

**Issue by Sajonara** [redbug26/crocods-ios#2]
Could you provide a release of an oecoreplugin-file, so that users not familiar with Xcode could use it? I tried compiling the source but always get errors.

Kind regards,

Alexander

**Comment by clobber** [comment]
@Sajonara Is it your mission to spam unrelated projects? This emulator port has nothing to do with OpenEmu, it's for iOS.

**Comment by Sajonara** [comment]
@clobber This link was provided on the official OpenEmu Wiki as a possible Core Plug-in. Hence I followed several of them and found at least some release files, and added them to my installation of OpenEmu. Others I downloaded myself but compilation with Xcode failed. So one should update the link to this project on the Wiki/Wishlist etc. Then people would not think this is related in any way.

**Comment by clobber** [comment]
Wat. That is a 'wish list' with links to source code, not a possible core plugin. A wish list is just that, a 'wish' list. The wiki is really easy to understand (it even tells you which ones were already ported!) so there is nothing that will be updated. You're not very bright, huh?

Kind regards,

clobber

**Comment by Sajonara** [comment]
@clobber Well obviously it is not. QED. I guess you get to the logic one day when you grow older. 

The wish list and the list of core plugins show links to projects which may be ported "and" some who are already available as a core plugin but not yet integrated into the app. Some of the latter could provide a release so people can implement it already.

Other than that you seem to be the typical superficial guy. Was nice meeting you #not and now it would be very kind of you, if you mind your own business and not to insult other people you don't know.

No regards.

**Comment by clobber** [comment]
No, I don't get the logic. Just because _you_ are an idiot doesn't mean everybody else has a problem _reading_ the wiki page. It's blatantly obvious:

> Strikethrough means they've already been ported. Feel free to port any that have not.

We don't link to _any_ ports that are "available as a core plugin but not yet integrated into the app" - that's just you lying trying to save face. You still have an open issue on someone else's repo that has nothing to do with anything! Mind boggling.

**Comment by Sajonara** [comment]
Well at least you tell your users they're idiots. That's a famous agenda, is it not? Casts a damning light at you and the project.

Sorry that you have not heard yet that in academics one single evidence of the contrary proofs you wrong. It is like that, take it or leave it. Makes no difference for me as you won't stop insulting people anyway. But that's okay for me, because it's your temper, not mine.

**Comment by clobber** [comment]
Idiot logic: "i r reading comprehension fail so dat means u r wrong hahaha, see, 'evidence' !!!"

> actually being this stupid

Your personal stupidity, bad experience and opinion of me is irrelevant to the project and myself - you are not even a blip on the radar, just meaningless text on a screen from an idiot nobody. I realize your feelings are hurt and you _really_ want to make sure you keep getting the last word in, because you are a humiliated special snowflake that cannot admit when they are wrong, but I will continue to insult you as required. It doesn't reflect negatively on me in the least.
